### ISSUE TITLE
部分webtoon点击阅读后导致闪退

### ISSUE THREAD

**Issue by HistoryMonitor** [Ehviewer-Overhauled/Ehviewer#734]
### 复现步骤 / Step to reproduce

1.点开画廊选择阅读
2.选用webtoon模式翻看一阵
3.再次点开后闪退循环，无法阅读

https://user-images.githubusercontent.com/54359196/215038190-c566274b-846c-430c-bb3f-a8dc6ed7e775.mp4

### 预期行为 / Expected behaviour

它应该可以正常阅读

### 实际行为 / Actual Behaviour

实际上闪退回上一个界面

### 备注 / Addition details

错误日志如下
[log-2023-01-27-15-41-55-601.zip](https://github.com/Ehviewer-Overhauled/Ehviewer/files/10516695/log-2023-01-27-15-41-55-601.zip)

### EhViewer 版本号 / EhViewer version code

1.8.5.3

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/Ehviewer-Overhauled/Ehviewer/actions/runs/4021029506

### Android 系统版本 / Android version

MIUI 12.0.1(PDICNXM)/Android 9

### 设备型号 / Device model

Redmi 6 Pro，arm64-v8a

### SoC 型号 / Soc model

高通骁龙625

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) 中的内容 / You have checked [Q&A](https://github.com/Ehviewer-Overhauled/Ehviewer/issues/61) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/Ehviewer-Overhauled/Ehviewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 CI 版本测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in latest CI version

**Comment by asuka-mio** [comment]
01-27 15:40:29.547  4097  4137 E OpenGLRenderer: GL error:  GL_INVALID_OPERATION
01-27 15:40:29.547  4097  4137 F OpenGLRenderer: glEGLImageTargetTexture2DOES error! GL_INVALID_OPERATION (0x502)
01-27 15:40:29.548  4097  4137 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 4137 (RenderThread), pid 4097 (tarsin.ehviewer)
01-27 15:40:29.900  4323  4323 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-27 15:40:29.902  4323  4323 I crash_dump64: performing dump of process 4097 (target tid = 4137)
01-27 15:40:29.917  4323  4323 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-27 15:40:29.917  4323  4323 F DEBUG   : Build fingerprint: 'xiaomi/sakura/sakura:9/PKQ1.180917.001/V12.0.1.0.PDICNXM:user/release-keys'
01-27 15:40:29.917  4323  4323 F DEBUG   : Revision: '0'
01-27 15:40:29.917  4323  4323 F DEBUG   : ABI: 'arm64'
01-27 15:40:29.917  4323  4323 F DEBUG   : pid: 4097, tid: 4137, name: RenderThread  >>> moe.tarsin.ehviewer <<<
01-27 15:40:29.917  4323  4323 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-27 15:40:29.917  4323  4323 F DEBUG   : Abort message: 'glEGLImageTargetTexture2DOES error! GL_INVALID_OPERATION (0x502)'
01-27 15:40:29.917  4323  4323 F DEBUG   :     x0  0000000000000000  x1  0000000000001029  x2  0000000000000006  x3  0000000000000008
01-27 15:40:29.917  4323  4323 F DEBUG   :     x4  4700000000000000  x5  4700000000000000  x6  4700000000000000  x7  00000000000080c7
01-27 15:40:29.917  4323  4323 F DEBUG   :     x8  0000000000000083  x9  52364a8f0b0b8de4  x10 0000000000000000  x11 fffffffc7ffffbdf
01-27 15:40:29.917  4323  4323 F DEBUG   :     x12 0000000000000001  x13 0000000000000001  x14 ffffffffffffffff  x15 4700000000000000
01-27 15:40:29.917  4323  4323 F DEBUG   :     x16 0000007875b9d2b8  x17 0000007875abcc50  x18 0000000000000010  x19 0000000000001001
01-27 15:40:29.917  4323  4323 F DEBUG   :     x20 0000000000001029  x21 0000007873f6cf58  x22 0000007873f6cf40  x23 0000007873f6d00e
01-27 15:40:29.918  4323  4323 F DEBUG   :     x24 0000007873f6cfdf  x25 0000007873f6cfbf  x26 0000007873f6cff4  x27 0000000000000502
01-27 15:40:29.918  4323  4323 F DEBUG   :     x28 0000007873f6cfdf  x29 00000077d4b70a20
01-27 15:40:29.918  4323  4323 F DEBUG   :     sp  00000077d4b709e0  lr  0000007875ab00c4  pc  0000007875ab00ec
01-27 15:40:29.955  4323  4323 F DEBUG   : 
01-27 15:40:29.955  4323  4323 F DEBUG   : backtrace:
01-27 15:40:29.955  4323  4323 F DEBUG   :     #00 pc 00000000000220ec  /system/lib64/libc.so (abort+116)
01-27 15:40:29.955  4323  4323 F DEBUG   :     #01 pc 0000000000008644  /system/lib64/liblog.so (__android_log_assert+296)
01-27 15:40:29.955  4323  4323 F DEBUG   :     #02 pc 00000000000e3de0  /system/lib64/libhwui.so (android::uirenderer::debug::GlesErrorCheckWrapper::assertNoErrors(char const*)+384)
01-27 15:40:31.389  4323  4323 E crash_dump64: cannot open libmiuindbg.so: No such file or directory
01-27 15:40:31.559  4333  4333 E tarsin.ehviewe: Not starting debugger since process cannot load the jdwp agent.

看起来是这个导致的闪退？

**Comment by asuka-mio** [comment]
不过我们现在已经不做显式的OpenGL 操作了
估计是系统的hwui实现有啥问题

**Comment by asuka-mio** [comment]
你把系统的hwui渲染器切换到vulkan看看试试？

**Comment by asuka-mio** [comment]
这个应该是你系统GPU 驱动的问题 
如果有人有别的想法觉得是阅读器的实现哪里有缺陷再reopen 吧

**Comment by asuka-mio** [comment]
btw，如果你有精力做测试的话 https://forum.xda-developers.com/t/rom-13-sakura-sakurain-pixel-experience-official-aosp.4390723/
可以试试这个 不过我也不敢保证一定能用 毕竟GPU 驱动应该是一样的

**Comment by asuka-mio** [comment]
https://github.com/vector-im/element-android/issues/4545

**Comment by asuka-mio** [comment]
https://github.com/vector-im/element-android/pull/7184

**Comment by asuka-mio** [comment]
@HistoryMonitor 看看这回行不行

**Comment by HistoryMonitor** [comment]
谢谢回复，暂时找不到更改手机渲染模式的方法，再琢磨下，有阅读器上的bug才叨扰发布
